batch_size: 64
eval_batch_size: 64
dropout: 0.0
lr: 0.0001
num_layers: 5
num_epochs: 50
down_epochs: 50
JK : "none"
task_names:
  - "cora_link"
  - "cora_node"
  - "mol_fs"
d_multiple:
  - 1.5
  - 2
  - 0.5
d_min_ratio:
  - 1
  - 1
  - 0.5
evaluate_names:
  - "cora_link"
dd_multiple:
  - 1.5
dd_min_ratio:
  - 1